# Site settings
title: Quirks
header-img: img/home-bg.png
email: alonso.jessicam@gmail.com
copyright_name: jesshasquirks
description: > # this means to ignore newlines until "baseurl:"
  embracing my inner nerd
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: jesshasquirks
github_username:  jesshasquirks
learn_profile: jesshasquirks
email_username: alonso.jessicam@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
